name: deploy
on:
  push: { branches: [ main ] }

permissions:
  id-token: write    # OIDC
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-main
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - run: npm ci
      - run: npm run build

      # GitHub→AWS を OIDC で接続（長期キー不要）
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::582802577320:role/GitHubActionsRole
          aws-region: ap-northeast-1

      # 1) assets は長期キャッシュで同期
      - name: Upload assets (long cache)
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete \
            --exclude index.html \
            --cache-control "public,max-age=31536000,immutable" \
            --metadata-directive REPLACE
        env: { S3_BUCKET: ${{ vars.S3_BUCKET }} }

      # 2) index.html はノーキャッシュで上書き
      - name: Upload index.html (no cache)
        run: |
          aws s3 cp dist/index.html s3://$S3_BUCKET/index.html \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html; charset=utf-8" \
            --metadata-directive REPLACE
        env: { S3_BUCKET: ${{ vars.S3_BUCKET }} }

      # CloudFront キャッシュ無効化
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $CF_DIST --paths "/*"
        env: { CF_DIST: ${{ vars.CF_DIST }} }
